version: "3.8"

services:
  auction-db:
    image: postgres:16-alpine
    container_name: auction-db
    restart: always
    env_file:
      - ./server/.env.dev
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432" # expose only if you need access from host machine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./db/init:/docker-entrypoint-initdb.d # optional init scripts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: nest_redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

networks:
  default:
    name: nest_network

volumes:
  postgres_data:
  redis_data:

